[project]
name = "adn-browser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cyvcf2>=0.31.1",
    "fastapi[standard]>=0.115.5",
    "pydantic>=2.10.1",
    "requests>=2.32.3",
    "uvicorn>=0.32.1",
]
